---

- run_once: yes
  block:
    - name: ARGOCD KUBERNETES | Download Kubernetes yaml file definition
      become: yes
      become_user: ubuntu
      get_url:
        url: https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
        dest: /tmp/argocd_install.yaml
        owner: ubuntu
        mode: 0644

    - name: ARGOCD KUBERNETES | Manage Kubernetes objects
      become: yes
      become_user: ubuntu
      k8s:
        namespace: "{{ argocd_k8s_namespace }}"
        src: /tmp/argocd_install.yaml
        state: "{{ argocd_action }}"
  always:
    - name: ARGOCD KUBERNETES | Clean installation
      become: yes
      become_user: ubuntu
      file:
        path: /tmp/argocd_install.yaml
        state: absent
